# @package _global_

dataset_name: i3db_Scene14

dataset:
  name: i3db_add_scene
  root_dir: "C:/humor/data/iMapper/i3DB"
  subject: male
  recording_name: Scene14

  train_frames: [ 0, 336, 4 ]
  val_frames: [ 335, 336, 4 ]
  test_frames:
    pose: [335, 524, 4]
    all: [0, 524, 1]
  predict_frames: [0, 0, 1]

  img_hw:
    - 450
    - 800

  resolution: -1
  white_background: false
  data_device: cuda
  eval: false
